spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  # 热部署
  devtools:
    restart:
      # 热部署生效
      enabled: true
      # 设置重启的目录,添加那个目录的文件需要restart
      additional-paths: src/main/java,src/main/resources
      # 不需实时加载
      exclude: db/** #,static/**
  # thymeleaf通用配置
  thymeleaf:
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
    # 可以单独在dev环境设置为false，避免修改模版重启服务器
    cache: false
    encoding: UTF-8
  # 解决返回结果中文乱码问题
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    # 文件上传 multipart config
    multipart:
      enabled: true
      location: /Users/wugang/code/java/elasticsearch-house/tmp/images/
      file-size-threshold: 5MB
      max-request-size: 20MB


# 拦截器配置
server:
  error:
    whitelabel:
      # 进入SpringBoot框架自动生成whitelabel页面
      enabled: false
    # error path配置
    path: /error

# 七牛云配置
qiniu:
  access-key: GVD-MVQEoOiJOt7yNBDo-JrOKWHB33eZN2JmDFC6
  secret-key: sHnl57ZXtStejn7GgY5VF3lnm1CxMJ3hcayexAWz
  bucket: lakers
  cdn:
      prefix: http://7xo6gy.com1.z0.glb.clouddn.com/
# 阿里云短信配置
aliyun:
  sms:
    access-key: LTAISjYxxr5qLmio
    secret-key: pkqEMJIcVQV8G5fkNEQNDQV7rsntKV
    template:
      code: SMS_95590008